### PR TITLE
Further Mobile Optimisations

### PR DESCRIPTION
**Pull request by LubricantJam**
This PR includes more mobile optimisations primarily for the modals on mobile as they squish too much, also a little converting to more Tailwind less style-sheets.

### CODE REVIEW

**Comment by LubricantJam** [comment]
@hrfee not sure what this compile error is related to as I'm on my phone, care to take a look? Works fine on a local instance.

**Comment by hrfee** [comment]
Accidentally just pushed to your fork lmao, but the jfa-go.com build was already broken. Compilation worked fine, and my commit should get rid of the errors.

**Comment by hrfee** [comment]
This looks great, also makes me realize i need to test on my phone more often 😂. One thing i did notice is that there's no longer a modal opening animation. I wasn't a big fan of the old one anyway but do you think a quick fade-in like there is for closing would look alright?

**Comment by LubricantJam** [comment]
I've never noticed one, where was it supposed to be? One can be added with the transition class and a duration-500 or something, I'm not on my PC at the minute to test.

**Comment by hrfee** [comment]
I've added a simple fade-in and fade-out which uses `animate-fade-in` and `animate-fade-out` classes. Everything else looks good so i'll merge.

**Pull request merged**
