### PR TITLE
Jellyseerr integration

### PR DESCRIPTION
**Pull request by hrfee**
Adds Jellyseerr integration on par with, or better than the current Ombi integration:
* Profiles for user and notification settings can be added in Settings > User Profiles, similarly to Ombi
* On invites w/ a profile w/ a Jellyseerr profile, and when creating accounts from the admin page, creating an account triggers the Jellyseerr user importer (on the created user only), resulting in a "Jellyfin User" which uses Jellyfin for auth, avoiding the need for password synchronization.
* Email, Discord and Telegram details are synchronized, as are contact preferences for each (hopefully)
* Existing accounts without a "Jellyseerr account" will have them automatically created.
* "Import existing users" setting triggers daemon to auto-import Jellyfin users.
  * Doesn't apply a profile, but
  * More granular "Modify Settings" feature in accounts allows application of *only* the Jellyseerr component,
  * So once the bulk of old users are imported, admin can select them all and "profile" them, and will likely only need to once.

* ~~Look into synchronizing disabled account state.~~ Jellyseerr correctly handles disabled accounts already.

Uses an API key found in Jellyseerr's settings page.

Basic API client available in the "jellyseer/" directory.

Also involved some cleanup of the various daemons.

### CODE REVIEW

**Comment by hrfee** [comment]
Merging since no real affect on other parts of the software, and I actual people to try it.

**Comment by Mavyre** [comment]
Hey! Thanks for the new feature. I'm migrating from Ombi to Jellyseerr. Which docker version of jfa-go can I use to get the Jellyseerr integration? It doesn't seem to be on the latest tag yet. Thanks again!

**Comment by hrfee** [comment]
> Hey! Thanks for the new feature. I'm migrating from Ombi to Jellyseerr. Which docker version of jfa-go can I use to get the Jellyseerr integration? It doesn't seem to be on the latest tag yet. Thanks again!

`hrfee/jfa-go:unstable`.

**Comment by xiNeRoar** [comment]
Is there any plan to merge to the main?

**Pull request merged**
