### PR TITLE
Log IPs

### PR DESCRIPTION
**Pull request by kimboslice99**

### CODE REVIEW

**Comment by hrfee** [comment]
Made IP logging optional, with two options in the "Advanced" settings folder, one for admins, and one for users. IP are logged alongside activities, and show in the UI.

**Comment by hrfee** [comment]
Also, I found that there's a built in `gc.ClientIP()` function, which checks "X-Real-IP", "X-Forwarded-For" and the actual request IP and finds the right one automatically. Could you check that the IP is still logged correctly for you?

**Comment by hrfee** [comment]
appears to work behind a reverse proxy for me, so i'm gonna merge.

**Comment by kimboslice99** [comment]
Very nice! Ya, with X-Real-IP provided it does log the right IP

**Comment by hrfee** [comment]
perfect timing 😂

**Comment by kimboslice99** [comment]
One issue, this doesnt matter for my purposes but nonetheless, I dont see the IPs logged in the UI activity tab,

**Comment by hrfee** [comment]
whoops yeah, I changed the name of a setting halfway through and forgot to change the name at the point where the value is loaded. fixed in f460bfc.

**Pull request merged**
